### ISSUE TITLE
Not able to input any text

### ISSUE THREAD

**Issue by radoslavov91** [melamriD365/Azure-Translatore-PCF#1]
I'm trying to use the PCV to get the text from the email body filed and translate it to another one, but I cannot do it.
I first insert the control into the Description field but then i wasn't able to input any text in it.
Now I've created a new field with Multiple lines of text here the translated text to go, but I guess something si wrong with my configuration.

![image](https://user-images.githubusercontent.com/54433534/105715741-a4032e80-5f26-11eb-9ad4-c2b6a7a26d80.png)

![image](https://user-images.githubusercontent.com/54433534/105715766-ad8c9680-5f26-11eb-9744-13c4221d1e6b.png)

**Comment by melamriD365** [comment]
Hello, 

In order to Translate the Email. you need to use the PCF on Description Field.  You will use the same field twice in your form. No need to create a new field. 

Please refer to the image below: 

![Azure-Translator-PCFissues1](https://user-images.githubusercontent.com/36016227/105718441-854e6900-5f21-11eb-8b5e-0f02e267912d.png)

**Comment by radoslavov91** [comment]
It working now, great!

Thanks :)

**Comment by radoslavov91** [comment]
It working now, great!

Thanks :)
